// Generated by CoffeeScript 1.4.0
(function() {
  var app, connection, express, mpd_state, net, server, socket;

  net = require('net');

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  socket = require('socket.io').listen(server);

  app.set('view engine', 'ejs');

  app.set('view options', {
    layout: false
  });

  app.use("/static", express["static"](__dirname + '/../static'));

  connection = net.createConnection({
    port: 6600
  });

  connection.setEncoding('utf-8');

  mpd_state = '';

  connection.on('connect', function() {
    return console.log('Connected');
  });

  connection.on('data', function(data) {
    console.log(data);
    return mpd_state = data;
  });

  socket.sockets.on('connection', function(socket) {
    return console.log('socket.io connected');
  });

  /*
  app.get '/', (req, res) ->
          res.render 'index__'
  */


  server.listen(3000);

}).call(this);
